### ISSUE TITLE
Simplify every day JS use

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/lib-util#15]
Things like this should be made easier and more robust with lib util. Basically handling undefined/null-issues.

`var email = req.params.email;`
`bean.description = __.nullOrValue(params.description);` - perhaps a __.nullOrValue-wrapper to the lib?

**Comment by poi33** [comment]
Cant this be solved with: 
`let value = params.description || null. `
Not a fan of using the java bridge just to check for if its a value :/ 
@ComLock any comments?

**Comment by ComLock** [comment]
I don't get what this issue is about...

In response to @poi33 suggestion on using double pipe you have to consider what is Truthy or Falsy in JavaScript.

- https://developer.mozilla.org/en-US/docs/Glossary/Truthy

- https://developer.mozilla.org/en-US/docs/Glossary/Falsy

Also undefined and null are not the same thing. Null is an actual value you can set or pass to functions.

So I would much rather it was __.undefinedOrValue ???

In Ecmascript 2015 deconstruction and default values was introduced, so you can do:

const hash = {
  one: {
    child: null
  }
};

const {
  one: {
    child = ''
  },
  two: {
    childOfTwo: null
  } = {}
};

At this point three constants exist:

- hash

- child

- childOfTwo

Both the value of child and childOfTwo is null.

**Comment by ComLock** [comment]
Looking at the documentation:
https://developer.enonic.com/docs/xp/stable/framework/java-bridge#nullorvalue

"Converts a JavaScript variable that is undefined to a Java null object. If the JavaScript variable is defined, it is returned as is."

Why do you want to have a Java null object when coding in JavaScript? What is wrong with just Javascript null?

**Comment by rymsha** [comment]
> Why do you want to have a Java null object when coding in JavaScript?
To be able to pass values to java methods, because there is no such thing as "undefined" argument in java.

It is not documented, but  `__.nullOrValue` handles `null` as `undefined` too - probably as "optimization". It has no side effects though, as null is always the same in java.

But I agree: the existence of `__.nullOrValue` method is questionable. In many places (internal libraries as well) pure js implementation is used instead 
```nullOrValue(arg) {if (arg === undefined) return null else return arg}``` and it looks more efficient.


And I agree with @poi33 too. I don't see how wrapping the bridge method would simplify things either. It would give yet another syntax to do the same thing - overall complicating code readability.

I suggest closing this issue 🙈
